<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-O1TFET3" failures="2" tests="9" name="Test" time="0.125" errors="0" timestamp="30 Apr 2023 17:14:21 GMT">
  <testcase classname="org.Day1.RerunTest" name="tc1" time="0.031"/>
  <testcase classname="org.Day1.RerunTest" name="tc2" time="0.0">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase classname="org.Day1.RerunTest" name="tc2" time="0.0">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase classname="org.Day1.RerunTest" name="tc2" time="0.0">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase classname="org.Day1.RerunTest" name="tc2" time="0.0">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at org.Day1.RerunTest.tc2(RerunTest.java:10)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase classname="org.Day1.RerunTest" name="tc3" time="0.016">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase classname="org.Day1.RerunTest" name="tc3" time="0.0">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase classname="org.Day1.RerunTest" name="tc3" time="0.0">
    <skipped/>
  </testcase> <!-- tc3 -->
  <testcase classname="org.Day1.RerunTest" name="tc3" time="0.015">
    <failure type="java.lang.AssertionError" message="Check TC3 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Check TC3 expected [true] but found [false]
at org.Day1.RerunTest.tc3(RerunTest.java:22)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- tc3 -->
</testsuite> <!-- Test -->
